---
name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install -g bats
      - run: bats -v
      - name: Run Ansible playbook
        id: ansible_run
        uses: jdhall75/ansible-playbook-action
        with:
          inventory_github: "https://github.com/jdhall75/ansible-inventory.git"
          vault_pass: ${{ secrets.VAULT_PASS }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.ansible_run.outputs.time }}"